### ISSUE TITLE
Additional input

### ISSUE THREAD

**Issue by Otaka** [JanNeuendorf/SVC16#2]
I believe that relying solely on mouse input significantly limits the use cases of the virtual console.
 If adding full keyboard support is not feasible, please consider adding a few buttons.
For example, like in the NES: **LEFT**, **RIGHT**, **UP**, **DOWN**, **A**, **B**, **START**, **SELECT**.
These are just 8 buttons that can be represented within a single byte using bit flags.

This approach would be sufficient for almost any game imaginable.

**Comment by JanNeuendorf** [comment]
Full keyboard input is definitely overkill and is also not very universal.
The NES idea is appealing.
I think that both the minimal selection of buttons and the idea of representing them with bit flags are very good.
The problem I see is that in 99% of cases, the inputs would be mapped to the keyboard. 
Keyboard inputs are just a bit more difficult to deal with due to things like repeat-rate etc. Maybe I am seeing a problem where there is none. 

One thought I have here is that I would not have these eight buttons in **addition** to the mouse keys. The **A** and **B** buttons could be the same input code as the left and right mouse keys. The mouse key is already stored as a bit flag with two bits. So the most logical extension might be to add six bits more.

**Comment by Otaka** [comment]
excellent😊
