### ISSUE TITLE
Opportunity  to leave features for expansions

### ISSUE THREAD

**Issue by JanNeuendorf** [JanNeuendorf/SVC16#9]
Now that the _expansion mechanism_ has been fixed and implemented, there is an opportunity to remove features from the spec. Those could then be restored using expansions if needed.

There are not many candidates for that. 

The screen is too essential. Without any output, the system is useless. 

That leaves one of the two inputs. Removing the button-input would leave only the mouse (without clicking).
This is probably not usable on its own and I want the system to be usable without the use of expansions.

The remaining option would be to leave only the NES inputs as core functionality with the idea that a mouse could be added as an expansion. This would, of course, be a drastic change. It would remove functionality that is already documented and implemented and it would break the demo-programs. There would be three benefits to that 
1. It makes everything a little bit simpler to explain.
2. It solves the awkward problem that we can not say if there is an external cursor or not. 
3. There would be a single default input-scheme

**Comment by xyloflake** [comment]
Hello @JanNeuendorf ! Sorry for not being active these days, been busy with the end of the year. Merry xmas!

I think actually offloading the entire inputs category to the expansion port would be much better as it would maintain uniformity. Like imagine having one "kind" of input being built in and implementing the other yourself. Pretty inconsistent, right? Instead, I propose we actually offload the entire inputs to the expansion port, and instead of letting people implement it themselves, we can implement it as a built in feature - just through the expansion port. This would be useful as:
1. It provides examples on how to use the expansion mechanism.
2. It provides stability and uniformity.
3. Components of the expansion port like inputs remain separate - simulating somewhat real life mechanism - you have peripheral controls separated.

In fact this way, if anyone wanted to expand the inputs to support the entire keyboard, they can. That's a nice thing to have.


That about breaking existing stuff, I think that's anticipated considering it's not declared stable yet (and there's been a warning banner in the readme). Also rewriting the programs might be a good idea as we can work on it to make more sense of the code since you've stated:
> the code might not have been compiled in a sensible way

**Comment by JanNeuendorf** [comment]
I don't think, that offloading the inputs entirely is a good option. This makes the system unusable without an expansion. The way I see it, the expansion mechanism is just a fail-safe so that someone who wants to use this but needs an additional feature can still use it. So it should not be required for basic functionality. This would also really constrain the possibilities for expansions because they would all need to handle input as well. 

As for point 1. I do see it, but this will probably soon be done with something else. My Idea was to resurrect the sound idea and add that as an example-expansion. 

>In fact this way, if anyone wanted to expand the inputs to support the entire keyboard, they can. That's a nice thing to have.

This is already possible. You are right that it is not super elegant since one of the inputs is read differently than the others but it is totally possible. 

The more I think about this, the less of a problem I see with the way it currently is. 
It is not very elegant, but it works well and it is not too hard to explain.  

(I also think that having the mouse by default is very good for people getting started. 
It is pretty easy to draw a cursor at the mouse position to see things moving on screen.)

(I am closing the issue because I don't think I am really going to change this.)
